"""
Water-tank reinforcement-learning environment adapted from CreateSimulinkEnvironmentAndTrainAgentExample.mlx
"""
from __future__ import annotations
import collections.abc
import gymnasium.spaces.box
import numpy
import numpy.typing
import typing
from . import _env
from . import _sl
__all__: tuple = ('RawEnv', 'GymEnv', 'rl_water')
class GymEnv:
    action_space: typing.ClassVar[gymnasium.spaces.box.Box]  # value = Box(-inf, inf, (1,), float64)
    metadata: typing.ClassVar[dict] = {'render.modes': list()}
    observation_space: typing.ClassVar[gymnasium.spaces.box.Box]  # value = Box([-inf -inf   0.], inf, (3,), float64)
    reward_range: typing.ClassVar[tuple] = (-101.0, 10.0)
    def __enter__(self) -> typing.Any:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, spec: _env.EnvSpec) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def close(self) -> None:
        ...
    def render(self) -> None:
        ...
    def reset(self, *, seed: typing.SupportsInt | typing.SupportsIndex | None = None, options: dict | None = None, preinit: collections.abc.Callable[[], None] = None, postinit: collections.abc.Callable[[], None] = None) -> tuple:
        ...
    def step(self, action: numpy.typing.NDArray[numpy.float64]) -> tuple:
        ...
    @property
    def model_class(self) -> rl_water:
        ...
    @property
    def spec(self) -> _env.EnvSpec:
        ...
    @property
    def unwrapped(self) -> typing.Any:
        ...
class RawEnv:
    def __init__(self) -> None:
        ...
    def reset(self) -> rl_water.ExtY_rl_water_T:
        ...
    @typing.overload
    def seed(self) -> list[int]:
        ...
    @typing.overload
    def seed(self, seed: typing.SupportsInt | typing.SupportsIndex) -> list[int]:
        ...
    def step(self, action: rl_water.ExtU_rl_water_T) -> rl_water.ExtY_rl_water_T:
        ...
    @property
    def model_class(self) -> rl_water:
        ...
class rl_water:
    class B_rl_water_T:
        dtype: typing.ClassVar[numpy.dtype[void]]  # value = dtype([('Sum1', '<f8'), ('Sum', '<f8')])
        def __copy__(self) -> rl_water.B_rl_water_T:
            ...
        def __deepcopy__(self, memo: dict) -> rl_water.B_rl_water_T:
            ...
        def __init__(self) -> None:
            ...
        def __repr__(self) -> str:
            ...
        def numpy(self) -> numpy.typing.NDArray[rl_water.B_rl_water_T]:
            ...
        @property
        def Sum(self) -> float:
            ...
        @Sum.setter
        def Sum(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def Sum1(self) -> float:
            ...
        @Sum1.setter
        def Sum1(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class ExtU_rl_water_T:
        dtype: typing.ClassVar[numpy.dtype[void]]  # value = dtype([('Action', '<f8')])
        def __copy__(self) -> rl_water.ExtU_rl_water_T:
            ...
        def __deepcopy__(self, memo: dict) -> rl_water.ExtU_rl_water_T:
            ...
        def __init__(self) -> None:
            ...
        def __repr__(self) -> str:
            ...
        def numpy(self) -> numpy.typing.NDArray[rl_water.ExtU_rl_water_T]:
            ...
        @property
        def Action(self) -> float:
            ...
        @Action.setter
        def Action(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class ExtY_rl_water_T:
        dtype: typing.ClassVar[numpy.dtype[void]]  # value = dtype({'names': ['State', 'Reward', 'Done'], 'formats': [('<f8', (3,)), '<f8', '?'], 'offsets': [0, 24, 32], 'itemsize': 40})
        Done: bool
        def __copy__(self) -> rl_water.ExtY_rl_water_T:
            ...
        def __deepcopy__(self, memo: dict) -> rl_water.ExtY_rl_water_T:
            ...
        def __init__(self) -> None:
            ...
        def __repr__(self) -> str:
            ...
        def numpy(self) -> numpy.typing.NDArray[rl_water.ExtY_rl_water_T]:
            ...
        @property
        def Reward(self) -> float:
            ...
        @Reward.setter
        def Reward(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def State(self) -> numpy.typing.NDArray[numpy.float64]:
            ...
    class InstP_rl_water_T:
        dtype: typing.ClassVar[numpy.dtype[void]]  # value = dtype([('h_goal', '<f8'), ('h_initial', '<f8')])
        def __copy__(self) -> rl_water.InstP_rl_water_T:
            ...
        def __deepcopy__(self, memo: dict) -> rl_water.InstP_rl_water_T:
            ...
        def __init__(self) -> None:
            ...
        def __repr__(self) -> str:
            ...
        def numpy(self) -> numpy.typing.NDArray[rl_water.InstP_rl_water_T]:
            ...
        @property
        def h_goal(self) -> float:
            ...
        @h_goal.setter
        def h_goal(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def h_initial(self) -> float:
            ...
        @h_initial.setter
        def h_initial(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class XDis_rl_water_T:
        dtype: typing.ClassVar[numpy.dtype[void]]  # value = dtype([('Integrator_CSTATE', '?'), ('H_CSTATE', '?')])
        H_CSTATE: bool
        Integrator_CSTATE: bool
        def __copy__(self) -> rl_water.XDis_rl_water_T:
            ...
        def __deepcopy__(self, memo: dict) -> rl_water.XDis_rl_water_T:
            ...
        def __init__(self) -> None:
            ...
        def __repr__(self) -> str:
            ...
        def numpy(self) -> numpy.typing.NDArray[rl_water.XDis_rl_water_T]:
            ...
    class X_rl_water_T:
        dtype: typing.ClassVar[numpy.dtype[void]]  # value = dtype([('Integrator_CSTATE', '<f8'), ('H_CSTATE', '<f8')])
        def __copy__(self) -> rl_water.X_rl_water_T:
            ...
        def __deepcopy__(self, memo: dict) -> rl_water.X_rl_water_T:
            ...
        def __init__(self) -> None:
            ...
        def __repr__(self) -> str:
            ...
        def numpy(self) -> numpy.typing.NDArray[rl_water.X_rl_water_T]:
            ...
        @property
        def H_CSTATE(self) -> float:
            ...
        @H_CSTATE.setter
        def H_CSTATE(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def Integrator_CSTATE(self) -> float:
            ...
        @Integrator_CSTATE.setter
        def Integrator_CSTATE(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    sample_time: typing.ClassVar[int] = 1
    rl_water_B: rl_water.B_rl_water_T
    rl_water_InstP: rl_water.InstP_rl_water_T
    rl_water_U: rl_water.ExtU_rl_water_T
    rl_water_X: rl_water.X_rl_water_T
    rl_water_XDis: rl_water.XDis_rl_water_T
    rl_water_Y: rl_water.ExtY_rl_water_T
    @staticmethod
    def terminate() -> None:
        ...
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def initialize(self) -> None:
        ...
    def skip(self, n: typing.SupportsInt | typing.SupportsIndex) -> None:
        """
        Skip n steps, using current model input
        """
    def step(self) -> None:
        ...
__author__: str = 'The MathWorks, Inc.'
__version__: str = '11.18'
