# Config version. DO NOT CHANGE.
__version__ = "1.0.0"

# Simulink model name without .slx suffix
model = "rl_water"

# Section simulink: settings about simulink code generation
[simulink]
    # Name of fixed-step solver
    # Option: "FixedStepAuto" | "FixedStepDiscrete" |"ode8"| "ode5" | "ode4" | "ode3" | "ode2" | "ode1" | "ode14x"
    solver = "FixedStepAuto"

    # Feature: support absolute time (e.g. <Clock> block)
    # Option: true | false
    absolute_time = false

    # Feature: integer arithmetic only, i.e. no float point math
    # Option: true | false
    integer_code = false

    # Feature: support non-finite number (Nan and +-Inf)
    # Option: true | false
    non_finite = true

    # Feature: support complex number
    # Option: true | false
    complex = false

    # Feature: support continuous time, for blocks with continuous state (e.g <Integrator> Block)
    # Option: true | false
    continuous_time = true

    # Feature: support variable size signal
    # Option: true | false
    variable_size_signal = false

    # Feature: support non-inlined s-function
    # Option: true | false
    non_inlined_sfcn = false

# Section cpp: settings about cpp interface
[cpp]
    # Name of model class
    class_name = "rl_water"

    # Optional namespace, leave empty or choose a valid c++ namespace identifier
    namespace = ""

# Section info: Information about the model
[info]
    # Description of the model
    # Option: "<auto>" (read it from Simulink model description) | "..."
    description = "Water-tank reinforcement-learning environment adapted from CreateSimulinkEnvironmentAndTrainAgentExample.mlx"

    # Version of the model
    # Option: "<auto>" (read it from Simulink model version) | "..."
    version = "<auto>"

    # Author of the model
    # Option: "<auto>" (read it from Simulink model creator) | "..."
    author = "<auto>"

    # License of the model:
    # Option: "<no-license>" (no license is specified) | "..."
    license = "<no-license>"
